import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar'
import "./styles/dk.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BackOffice',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " dark-theme text-white"}>
        <Navbar metadata={metadata}/>

        {children}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossOrigin="anonymous"></script>
      </body>
    </html>
  )
}
